apiVersion: v1
kind: Service
metadata:
  name: netflix-app
spec:
  type: LoadBalancer # Changed from NodePort to LoadBalancer
  ports:
  - port: 80        # The port you type in the browser
    targetPort: 80  # The port your container is listening on
  selector:
    app: netflix-app

